name: Trigger QA Workflow After PR Merge 
on: 
   pull_request:  
       branches: 
            - main 
       types: 
       - closed           
jobs: 
   trigger-qa-workflow: 
     if: ${{ github.event.pull_request.merged == true }}
     runs-on: ubuntu-latest 

     steps:
         -  name: Trigger QA repository workflow 
            run: |
             curl --fail-with-body --request POST --url "https://api.github.com/repos/kavyag123456/qa-repo-poc/actions/workflows/main.yml/dispatches" --header "Accept: application/vnd.github+json"
               --header "Authorization: Bearer ${{ secrets.QA_REPO_PAT }}" \
               --header "X-GitHub-Api-Version: 2022-11-28" \
               --data '{"ref":"main"}'
  
